spring:
  application:
    name: product-service
  
  # 資料庫配置
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console 配置
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
      process: true
      system: true
      logback: true
      circuitbreaker: true

# Resilience4j Circuit Breaker 配置
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
    instances:
      order-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      order-service:
        baseConfig: default
